### PR TITLE
test: adding lint script and ci

### PR DESCRIPTION
**Pull request by martinheidegger**
This PR adds standard linting _(same as in other sibling projects in a `lint` script)_, a github action and updates all code to pass.

### CODE REVIEW

**Review by srl295 — APPROVED** [review]
looks great to me!

**Comment by srl295** [comment]
@obensource hi, ought i to have merge access?

**Review by obensource — APPROVED** [review]
Wow, great work – thanks for this! 🙌

LGTM! 🚀

**Comment by obensource** [comment]
@srl295 yes, yes you should lol. 👍

**Comment by srl295** [comment]
ok, FWIW I don't…

**Comment by obensource** [comment]
@srl295 It looks like ownership / merge access hasn't been set to the i18n or various individuals. Going to reach out for help there. 👍

**Comment by obensource** [comment]
@srl295 reaching out to people via the node/i18n repo in the OpenJSF slack, we'll get this resolved asap. 👍

**Comment by obensource** [comment]
@srl295 going to sort this out sync with @bnb tomorrow 😎

**Comment by srl295** [comment]
@martinheidegger congrats on the first post-move PR!

**Comment by srl295** [comment]
@martinheidegger 
in CI:
> Note: Your node was not compiled with the ‘small-icu’ case, so the ICU data is not customizable through this script. Exitting.

so, need somehow to get a small-icu case. Probably from docker?

**Pull request merged**
